server:
  port: 8080
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: never
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
#  security:
#    user:
#      name: John
#      password: John

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      '[hibernate.format_sql]': true

logging:
  file:
    name: logs/studentapp.log
  pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"
  level:
    '[org.springframework.web]': WARN
    '[org.hibernate]': INFO
    '[com.tpe]': INFO




